/* tslint:disable */
/* eslint-disable */
/**
 * Waiting List Api
 * Ambulance Counseling Project API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: xkoricansky@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLogin200Response
 */
export interface UserLogin200Response {
    /**
     * JWT token for authenticated requests
     * @type {string}
     * @memberof UserLogin200Response
     */
    token?: string;
}

/**
 * Check if a given object implements the UserLogin200Response interface.
 */
export function instanceOfUserLogin200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserLogin200ResponseFromJSON(json: any): UserLogin200Response {
    return UserLogin200ResponseFromJSONTyped(json, false);
}

export function UserLogin200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLogin200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': !exists(json, 'token') ? undefined : json['token'],
    };
}

export function UserLogin200ResponseToJSON(value?: UserLogin200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
    };
}

